services:
  client:
    build:
      context: ./client/PeerGrade
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/PeerGrade:/usr/client
      - client-node-modules:/usr/client/node_modules
    depends_on:
      - server
      - postgres

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/server
      - server-node-modules:/usr/server/node_modules
    depends_on:
      - postgres
    
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: COSC 499
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456ab
    ports:
      - "5433:5433"
    volumes:
      - ./database:/var/lib/postgresql/data

volumes:
  client-node-modules:
  server-node-modules: