services:

  db:
    image: postgres:latest
    env_file:
      - ./server/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.local
      args:
      - BACKEND_PORT=${BACKEND_PORT} 
      - DB_NAME=${DB_NAME} 
      - DB_PORT=${DB_PORT} 
    env_file:
      - ./server/.env
    ports:
      - "${BACKEND_PORT}:5001"
    volumes:
      - ./server:/usr/server
      - server-node-modules:/usr/server/node_modules
    depends_on:
      - db 

  client:
    build:
      context: ./client/PeerGrade
      dockerfile: Dockerfile
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
    env_file:
      - ./client/PeerGrade/.env
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./client/PeerGrade:/usr/client
      - client-node-modules:/usr/client/node_modules
    depends_on:
      - server
      - db

volumes:
  client-node-modules:
  server-node-modules:
  db-data: 