version: '3'
services:

  client:
    build:
      context: ./client/PeerGrade
      dockerfile: Dockerfile
    env_file:
      - ./client/PeerGrade/frontend.env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./client/PeerGrade:/usr/client
      - client-node-modules:/usr/client/node_modules
    depends_on:
      - server
      - postgres

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/backend.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./server:/usr/server
      - server-node-modules:/usr/server/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./database.env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./database:/var/lib/postgresql/data

volumes:
  client-node-modules:
  server-node-modules: