services:
# TODO 
# Refactor compose so that prisma commands work and sync together 
# JOSH 
# DO NOT USE FOR API QUERIES WILL NOT WORK YET
  db:
    container_name: peergrade_db
    image: postgres:latest
    # env_file:
    #   - ./server/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    container_name: peergrade_server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
      args:
      - BACKEND_PORT=${BACKEND_PORT} 
      - DB_NAME=${DB_NAME} 
      - DB_PORT=${DB_PORT} 
    env_file:
      - ./server/.env 
    ports:
      - ${BACKEND_PORT}:5001
    volumes:
      - ./server:/usr/server
      - server_node_modules:/usr/server/node_modules
    depends_on:
      - db 

  client:
    container_name: peergrade_client
    build:
      context: ./client/PeerGrade
      dockerfile: Dockerfile
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
    env_file:
      - ./client/PeerGrade/.env
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./client/PeerGrade:/usr/client 
      - client_node_modules:/usr/client/node_modules
    depends_on:
      - server
      - db

volumes:
  db-data: 
  server_node_modules:
  client_node_modules: