services:

  db:
    container_name: peergrade-db-dev
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    container_name: peergrade-server-dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev
      args:
      - BACKEND_PORT=${BACKEND_PORT} 
      - DB_NAME=${DB_NAME} 
      - DB_PORT=${DB_PORT} 
    env_file:
      - ./server/.env 
    ports:
      - ${BACKEND_PORT}:5001 
      - 5555:5555
    volumes:
      - ./server:/usr/server
      - server_node_modules:/usr/server/node_modules
    depends_on:
      - db 

  client:
    container_name: peergrade-client-dev
    build:
      context: ./client/PeerGrade
      dockerfile: Dockerfile.dev
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
    env_file:
      - ./client/PeerGrade/.env
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./client/PeerGrade:/usr/client 
      - client_node_modules:/usr/client/node_modules
    depends_on:
      - server
      - db

volumes:
  db-data: 
  server_node_modules:
  client_node_modules: