# Github Action/Bash Script to send Discord Notifications when an Issue is assigned

# First maps all of of the users to their Discord IDs, then loops through a Json array
# of the assignee(s) and adds them to a list of embedded discord mentiond (the <@ID> format)
# The script then sends a notification to Discord with the assignee(s) mentioned with curl and
# the data is sent as Discord's embedded json message format
name: Discord Notification on Issue Assigned

on:
  issues:
    types: [assigned]

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification to Discord
      run: |
        declare -A map 
        map["JoshFarwig"]="<@239921359847817216>"
        map["mahirr476"]="<@706320638301962291>"
        map["Bhavya290223"]="<@788404909107052546>"
        map["namekeptanonymous"]="<@312212189056466944>"

        ASSIGNEE=$(echo '${{ toJson(github.event.issue.assignee) }}' | jq -r '.login')
        MENTION="${map[$ASSIGNEE]}"

        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{
               "username": "Github",
               "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
               "content": "'"${MENTION}"'",
               "embeds": [{
                 "title": "Issue Assigned",
                 "url": "${{ github.event.issue.html_url }}",
                 "author": {
                   "name": "${{ github.event.issue.user.login }}",
                   "icon_url": "${{ github.event.issue.user.avatar_url }}"
                 },
                 "fields": [
                   {"name": "Title", "value": "${{ github.event.issue.title }}", "inline": false},
                   {"name": "Assignee", "value": "'"${ASSIGNEE}"'", "inline": false}
                 ]
               }]
             }' \
             ${{ secrets.ISSUE_ASSIGN_DISCORD_WEBHOOK_URL }}